CREATE TABLE UTENTE (
	Username VARCHAR (10) PRIMARY KEY,
	Email VARCHAR (30) UNIQUE NOT NULL,
	Password VARCHAR (255) NOT NULL
);

CREATE TABLE CARTA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Valore INT (2) NOT NULL,
	Seme VARCHAR (6) NOT NULL,
	CONSTRAINT unique_v_s UNIQUE(Valore, Seme)
);

CREATE TABLE IMMAGINI (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CARTA_ID INT UNIQUE NOT NULL,
	FOREIGN KEY (CARTA_ID) REFERENCES CARTA(ID) ON DELETE CASCADE,
	URL_IMM VARCHAR(255) NOT NULL
);

CREATE TABLE PARTITAPC(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	U_Username VARCHAR (10) NOT NULL,
	FOREIGN KEY (U_Username) REFERENCES UTENTE(Username) ON DELETE CASCADE,
	Status VARCHAR(10) NOT NULL,
	PuntiBanco INT NOT NULL,
	PuntiUtente INT NOT NULL
);

ALTER TABLE PARTITAPC
ADD DataInserimento TIMESTAMP;
ALTER TABLE PARTITAPC
ADD DataModifica TIMESTAMP NULL;

ALTER TABLE PARTITAPC
MODIFY COLUMN DataInserimento TIMESTAMP NULL;